/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeRouteImport } from './routes/me'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GGroupIdRouteImport } from './routes/g.$groupId'
import { Route as AdminInstanceRouteImport } from './routes/admin.instance'

const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GGroupIdRoute = GGroupIdRouteImport.update({
  id: '/g/$groupId',
  path: '/g/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstanceRoute = AdminInstanceRouteImport.update({
  id: '/admin/instance',
  path: '/admin/instance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/admin/instance': typeof AdminInstanceRoute
  '/g/$groupId': typeof GGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/admin/instance': typeof AdminInstanceRoute
  '/g/$groupId': typeof GGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/admin/instance': typeof AdminInstanceRoute
  '/g/$groupId': typeof GGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/me' | '/admin/instance' | '/g/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/me' | '/admin/instance' | '/g/$groupId'
  id: '__root__' | '/' | '/me' | '/admin/instance' | '/g/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeRoute: typeof MeRoute
  AdminInstanceRoute: typeof AdminInstanceRoute
  GGroupIdRoute: typeof GGroupIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$groupId': {
      id: '/g/$groupId'
      path: '/g/$groupId'
      fullPath: '/g/$groupId'
      preLoaderRoute: typeof GGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/instance': {
      id: '/admin/instance'
      path: '/admin/instance'
      fullPath: '/admin/instance'
      preLoaderRoute: typeof AdminInstanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeRoute: MeRoute,
  AdminInstanceRoute: AdminInstanceRoute,
  GGroupIdRoute: GGroupIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
